const mongoose = require("mongoose");
const Quiz = require("../model/quiz.js");

/* ================================
   ADVANCED SPLUNK DASHBOARDS QUIZ
================================ */

const splunkAdvancedDashboardsQuiz = {
  title: "T.O Analytics Splunk Class 7 Quiz",
  description:
    "Advanced quiz covering Splunk dashboards, tokens, dashboard studio, performance, and design decisions.",
  questions: [
    {
      question:
        "Which statement BEST explains why dashboards are described as “not about SPL”?",
      options: [
        "SPL is auto-generated by Splunk",
        "Dashboards focus on data ingestion",
        "Dashboards prioritize instant communication of insights",
        "SPL is replaced by visual components",
      ],
      correct:
        "Dashboards prioritize instant communication of insights",
      reason:
        "Dashboards exist to communicate insights quickly. SPL is only the engine behind the visualization."
    },
    {
      question:
        "Which dashboard characteristic MOST directly reduces MTTR (Mean Time to Resolution)?",
      options: [
        "Scheduled refresh intervals",
        "Use of summary indexes",
        "Drilldowns that expose root-cause searches",
        "Panel color customization",
      ],
      correct:
        "Drilldowns that expose root-cause searches",
      reason:
        "Drilldowns allow analysts to jump directly from high-level indicators into detailed investigations."
    },
    {
      question:
        "Why do executives typically prefer dashboards with minimal filters?",
      options: [
        "They do not understand SPL",
        "They require static results",
        "They need high-level KPIs without operational noise",
        "Filters slow down searches",
      ],
      correct:
        "They need high-level KPIs without operational noise",
      reason:
        "Executives want summarized KPIs and trends without interacting deeply with raw data."
    },
    {
      question:
        "Which use case BEST aligns with real-time dashboard updates?",
      options: [
        "Quarterly revenue analysis",
        "Capacity planning",
        "Security breach detection",
        "Historical trend analysis",
      ],
      correct: "Security breach detection",
      reason:
        "Security incidents require immediate visibility and rapid response."
    },
    {
      question:
        "What limitation does Dashboard Studio remove compared to Classic XML dashboards?",
      options: [
        "Token usage",
        "XML-based layout constraints",
        "Time picker support",
        "Drilldown functionality",
      ],
      correct: "XML-based layout constraints",
      reason:
        "Dashboard Studio removes rigid XML layout rules and allows flexible, modern layouts."
    },
    {
      question:
        "Why do many enterprises still rely heavily on Classic Dashboards?",
      options: [
        "Dashboard Studio lacks tokens",
        "Classic dashboards support inline JavaScript and advanced forms",
        "Studio dashboards do not support charts",
        "Classic dashboards refresh faster",
      ],
      correct:
        "Classic dashboards support inline JavaScript and advanced forms",
      reason:
        "Many production dashboards depend on complex form logic and inline JavaScript."
    },
    {
      question:
        "Which dashboard framework offers pixel-perfect positioning without XML?",
      options: [
        "Simple XML",
        "HTML dashboards",
        "Dashboard Studio",
        "Classic Form dashboards",
      ],
      correct: "Dashboard Studio",
      reason:
        "Dashboard Studio uses a modern layout engine instead of XML positioning."
    },
    {
      question:
        "Which scenario MOST requires a Classic Dashboard over Dashboard Studio?",
      options: [
        "Executive KPI visualization",
        "SOC monitoring dashboard",
        "Complex chained input forms",
        "Static reporting",
      ],
      correct: "Complex chained input forms",
      reason:
        "Classic dashboards handle advanced token chaining and form logic more reliably."
    },
    {
      question:
        "Why is creating a dashboard directly from a search considered easiest?",
      options: [
        "It skips SPL validation",
        "It auto-detects index permissions",
        "It auto-populates panel searches and visualizations",
        "It creates summary indexes automatically",
      ],
      correct:
        "It auto-populates panel searches and visualizations",
      reason:
        "Splunk converts an existing search into a panel automatically."
    },
    {
      question:
        "What happens internally when a dashboard is saved after choosing a chart?",
      options: [
        "SPL is optimized",
        "A panel definition is created referencing the SPL",
        "Tokens are auto-generated",
        "The search becomes a saved search",
      ],
      correct:
        "A panel definition is created referencing the SPL",
      reason:
        "Splunk stores the panel configuration and links it to the underlying search."
    }
  ],
};

/* ================================
   DATABASE SEEDER
================================ */

const MONGO_URI =
  "mongodb+srv://fpasamuelmayowa51:5iX35jgh9yB9P6Im@cluster0.unk3ntp.mongodb.net/datausers";

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Connected to DB ✅");

    // Remove old version of this quiz
    await Quiz.Quiz.deleteMany({
      title: "T.O Analytics Splunk Class 7 Quiz",
    });

    // Save new quiz
    await Quiz.Quiz.create(splunkAdvancedDashboardsQuiz);

    console.log(
      "T.O Analytics Splunk Class 7 Quiz 🚀"
    );
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();
