// Portable, deliberately bounded SPL subset used by advanced practice.
// Browser copies are generated by scripts/syncAdvancedLab.js.
function splitPipeline(query) {
  const parts = []; let part = ''; let quoted = false;
  for (const char of query) {
    if (char === '"') quoted = !quoted;
    if (char === '|' && !quoted) { parts.push(part.trim()); part = ''; }
    else part += char;
  }
  if (quoted) throw new Error('Close the double quote in your search.');
  parts.push(part.trim());
  if (parts.some(p => !p)) throw new Error('Every pipe must be followed by a command.');
  return parts;
}

// Greedy glob matching avoids executing user-controlled regular expressions.
function wildcardMatch(input, pattern) {
  const text = String(input).toLowerCase(); const glob = pattern.toLowerCase();
  let i = 0; let j = 0; let star = -1; let retry = 0;
  while (i < text.length) {
    if (j < glob.length && glob[j] !== '*' && glob[j] === text[i]) { i++; j++; }
    else if (glob[j] === '*') { star = j++; retry = i; }
    else if (star !== -1) { j = star + 1; i = ++retry; }
    else return false;
  }
  while (glob[j] === '*') j++;
  return j === glob.length;
}

function filter(rows, expression) {
  const tokens = expression.match(/(?:[^\s"]|"[^"]*")+/g) || [];
  const tests = tokens.filter(t => t !== 'AND').map(token => {
    if (/^(OR|NOT)$/i.test(token)) throw new Error('OR and NOT are not supported in this practice track. Use explicit field filters.');
    const match = token.match(/^(\w+)(>=|<=|!=|=|>|<)(.+)$/);
    if (!match) {
      if (/[=<>!()]/.test(token)) throw new Error('Use field=value without spaces around the operator.');
      return row => JSON.stringify(row).toLowerCase().includes(token.replace(/^"|"$/g, '').toLowerCase());
    }
    const [, field, op, raw] = match;
    const value = raw.replace(/^"|"$/g, '');
    return row => {
      if (row[field] == null) return false;
      if (op === '=') return wildcardMatch(row[field], value);
      if (op === '!=') return !wildcardMatch(row[field], value);
      const a = Number(row[field]); const b = Number(value);
      if (!Number.isFinite(a) || !Number.isFinite(b)) throw new Error('Numeric comparisons require numeric fields and values.');
      return op === '>' ? a > b : op === '>=' ? a >= b : op === '<' ? a < b : a <= b;
    };
  });
  return rows.filter(row => tests.every(test => test(row)));
}

function aggregate(rows, body) {
  const match = body.match(/^(count|sum\((\w+)\)|avg\((\w+)\))(?:\s+AS\s+(\w+))?(?:\s+BY\s+([\w, ]+))?$/i);
  if (!match) throw new Error('Use stats count AS total BY field, or stats sum(field)/avg(field) AS total BY field.');
  const [, fn, sumField, avgField, alias, by] = match;
  const fields = by ? by.split(/[\s,]+/).filter(Boolean) : [];
  const groups = new Map();
  rows.forEach(row => {
    const key = JSON.stringify(fields.map(f => row[f] ?? null));
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(row);
  });
  if (!fields.length && !rows.length) groups.set('[]', []);
  return [...groups.values()].map(group => {
    const result = Object.fromEntries(fields.map(f => [f, group[0]?.[f] ?? null]));
    const values = group.map(row => row[sumField || avgField]).filter(v => v != null).map(Number).filter(Number.isFinite);
    const sum = values.reduce((a, b) => a + b, 0);
    result[alias || fn.toLowerCase()] = sumField ? sum : avgField ? (values.length ? sum / values.length : null) : group.length;
    return result;
  });
}

function bucket(time, minutes) {
  const [h, m] = time.split(':').map(Number);
  const total = Math.floor((h * 60 + m) / minutes) * minutes;
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}:00`;
}

function executeAdvanced(events, query, metadata) {
  if (typeof query !== 'string' || !query.trim() || query.length > 3000) throw new Error('Enter a search between 1 and 3,000 characters.');
  const commands = splitPipeline(query.trim());
  let rows = events.map(row => ({ ...row, index: metadata.index, sourcetype: metadata.sourcetype }));
  rows = filter(rows, commands.shift().replace(/^search\s+/i, ''));
  rows = rows.map(event => { const row = { ...event }; delete row.index; delete row.sourcetype; return row; });
  for (const command of commands) {
    const name = command.split(/\s/)[0].toLowerCase();
    const body = command.slice(name.length).trim();
    if (!body) throw new Error(`Add arguments after ${name}.`);
    if (name === 'search' || name === 'where') rows = filter(rows, body);
    else if (name === 'stats') rows = aggregate(rows, body);
    else if (name === 'table' || name === 'fields') {
      if (!/^[\w, ]+$/.test(body)) throw new Error('List field names separated by spaces.');
      const fields = body.split(/[\s,]+/).filter(Boolean);
      rows = rows.map(row => Object.fromEntries(fields.map(f => [f, row[f] ?? null])));
    } else if (name === 'sort') {
      const match = body.match(/^([-+])?\s*(\w+)$/);
      if (!match) throw new Error('Use sort field or sort - field.');
      rows.sort((a, b) => String(a[match[2]] ?? '').localeCompare(String(b[match[2]] ?? ''), 'en', { numeric: true }) * (match[1] === '-' ? -1 : 1));
    } else if (name === 'head') {
      if (!/^\d+$/.test(body) || Number(body) < 1 || Number(body) > 500) throw new Error('Use head with a number from 1 to 500.');
      rows = rows.slice(0, Number(body));
    } else if (name === 'dedup') {
      if (!/^\w+(?:\s+\w+)*$/.test(body)) throw new Error('Use dedup followed by field names.');
      const seen = new Set(); const fields = body.split(/\s+/);
      rows = rows.filter(row => { const key = JSON.stringify(fields.map(f => row[f])); if (seen.has(key)) return false; seen.add(key); return true; });
    } else if (name === 'timechart') {
      const match = body.match(/^span=([1-9]\d*)(m|h)\s+(count|sum\(\w+\))(?:\s+BY\s+(\w+))?$/i);
      if (!match) throw new Error('Use timechart span=5m count BY field or timechart span=5m sum(field).');
      const [, n, unit, fn, by] = match;
      const minutes = Number(n) * (unit.toLowerCase() === 'h' ? 60 : 1);
      const grouped = aggregate(rows.map(row => ({ ...row, _time: bucket(row._time, minutes) })), `${fn} AS value BY _time${by ? ' ' + by : ''}`);
      if (!by) rows = grouped;
      else {
        const series = [...new Set(grouped.map(row => String(row[by])))];
        const times = new Map();
        grouped.forEach(row => {
          if (!times.has(row._time)) times.set(row._time, Object.fromEntries([['_time', row._time], ...series.map(s => [s, 0])]));
          Object.defineProperty(times.get(row._time), String(row[by]), { value: row.value, enumerable: true, configurable: true, writable: true });
        });
        rows = [...times.values()];
      }
      rows.sort((a, b) => a._time.localeCompare(b._time));
    } else throw new Error(`Unsupported command: ${name}. Supported: search, where, stats, table, fields, sort, head, dedup, timechart.`);
  }
  return { rows, count: rows.length, scanned: events.length };
}

function sameResults(actual, expected, ordered = false) {
  const canonical = rows => rows.map(row => JSON.stringify(Object.keys(row).sort().map(key => [key, row[key]])));
  const a = canonical(actual); const b = canonical(expected);
  if (!ordered) { a.sort(); b.sort(); }
  return JSON.stringify(a) === JSON.stringify(b);
}

module.exports = { executeAdvanced, sameResults };
