// Run from this repository after changing advanced practice services.
const fs = require('node:fs');
const path = require('node:path');
const target = path.resolve(__dirname, '../../t-o-analytics/src/lib/advancedLab');
fs.mkdirSync(target, { recursive: true });
for (const name of ['advancedSpl', 'advancedScenarios', 'advancedPractice']) {
  const source = fs.readFileSync(path.join(__dirname, '../services', name + '.js'), 'utf8')
    .replace(/const \{ (.+) \} = require\('\.\/(.+)'\);/g, "import { $1 } from './$2.js';")
    .replace(/module\.exports = \{ (.+) \};/g, 'export { $1 };');
  fs.writeFileSync(path.join(target, name + '.js'), '// Generated by to-backendapi-v1/scripts/syncAdvancedLab.js. Do not edit directly.\n' + source);
}
console.log('Advanced lab browser modules synchronized.');
